version: '3'

services:
    app:
        build:
            context: .
        ports:
        - "8080:80"
        volumes:
        - .:/var/www/html

    test:
        build:
            context: .
        command: ["php", "vendor/bin/phpunit"]
        volumes:
        - .:/var/www/html